dist: xenial
language: python

services:
  - postgresql

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - nightly

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
  - pip install --upgrade pytest

install: pip install -e .

script:
  - py.test -vv --cov-report term-missing:skip-covered --cov=sqlalchemy_dict

after_success: if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
  pip install -r requirements-doc.txt &&
  sphinx-build -nW -b html doc doc/_build/html &&
  touch doc/_build/html/.nojekyll &&
  touch doc/_build/html/_static/.nojekyll &&
  travis_retry coveralls ; fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: doc/_build/html
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = '3.5'
